### PR TITLE
Make `create_sup_file()` actually use the argument `simname` (fix issue #21)

### PR DESCRIPTION
**Pull request by ohexel**
Replace hard-coded `sup.fn <- "socsim.sup"` with logic that uses simname as the file name or at least its stub. Inform user of file name and full path via print statement before returning the file name.

### CODE REVIEW

**Comment by ohexel** [comment]
Added a default `simname` to avoid errors when no `simname` is supplied by user. Simplified `ifelse(grepl())` into standard `if` statement.

**Comment by tomthe** [comment]
very good. But now it has merge conflicts that have to be resolved.

**Comment by ohexel** [comment]
Fixed?

**Comment by tomthe** [comment]
yes, fixed.

**Pull request merged**
